import Head from 'next/head'
import { Inter } from '@next/font/google'
import Container from 'src/components/container'
import Hero from 'components/hero'
import Review from 'components/review'
import Information from 'components/information'
import MenuInformation from 'components/menuInformation'
import InstagramComponent from 'components/instagram'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Review />
      <MenuInformation />
      <Container>
        {/* <Beans /> */}
        <Information />
        <InstagramComponent />
      </Container>

      {/* <Beans /> */}
    </>
  )
}
